language: swift
osx_image: xcode8
env:
- XAMARIN_DEVICES_ID_PR=92132fb4 XAMARIN_DEVICES_ID_CRON=a3dab23a
before_script: "./scripts/add-keys.sh"
after_script: "./scripts/remove-key.sh"
script:
- "./scripts/buildPrebidMobile.sh"